name: Cypress

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v2
        with:
          node-version: 14
        # do not use actions/cache@v2 here or one needs to handle caching
        # https://docs.cypress.io/guides/continuous-integration/introduction#Caching
      - run: yarn
      - run: yarn test:cypress:ci
